repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.3
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: local
    hooks:
      - id: prettier
        name: run format
        language: system
        entry: bash -c 'cd frontend && pnpm format'
        pass_filenames: false
        types_or: [ ts, javascript, scss, css, yaml, json, vue ]
        files: ^frontend/
  - repo: local
    hooks:
      - id: lint
        name: run lint
        language: system
        entry: bash -c 'cd frontend && pnpm lint'
        pass_filenames: false
        types_or: [ ts, javascript, scss, css, yaml, json, vue ]
        files: ^frontend/
