checks:
  python:
    code_rating: true
    duplicate_code: true
  javascript:
    no_comma_dangle: true
    code_rating: true
    duplicate_code: true


build:
  environment:
      python: 3.12
  nodes:
    analysis:
      tests:
        override:
          - py-scrutinizer-run

filter:
  excluded_paths:
    - 'tests/*'
    - 'fixtures/*'
    - 'atramhasis/scripts/*'
