name: Atramhasis backend tests

on:
  push:
    paths:
      - atramhasis/**
      - scripts/**
      - tests/**
      - '!atramhasis/static/**'
      - .github/workflows/atramhasis_backend.yaml
      - pyproject.toml
      - requirements*.txt

jobs:
  test:
    runs-on: self-hosted
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: |
            3.10
            3.11
            3.12

      - name: Install python requirements
        env:
          HATCH_BUILD_NO_HOOKS: true
        working-directory: ./
        run: |
          pip --version
          pip install pip-tools
          pip-sync requirements-dev.txt
          pip install -e .

      - name: Python tests
        run: pytest tests --exitfirst --capture=no -vvv --full-trace
